repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types:
          - "python"
        args:
          - "--line-length=89"
          - "--skip-string-normalization"
      - id: isort
        name: isort
        entry: isort
        language: system
        types:
          - "python"
        args:
          ["--profile", "black"]
      - id: docformatter
        name: docformatter
        entry: docformatter
        language: system
        types:
          - "python"
        args:
          - "--in-place"
          - "--wrap-summaries=72"
          - "--pre-summary-newline"
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types:
          - "python"
        args:
          - "--max-line-length=89"